# Hide and Seek Config
# 鬼の難易度はマイクラの難易度と共通しています。
# ピースフルだと鬼は素手でワンパンできるようになります。
# messageはすべて表示されるメッセージです。好きなように変更してください。

# コマンドのヘルプは単体で実行すれば閲覧できます
# /hideandseekがメインコマンドです

# アイテムやイベントなどのstateはenableかdisableに設定してください。

timer:
  # タイマーのデフォルト値
  default: 300

lobby:
  # 必要な人数がそろってからスタートするまでの秒数
  startGame: 20
  # 鬼と逃げの比率(鬼:逃げ)
  seekerRatio: 1
  hiderRatio: 5
  # スタートに必要な最低人数(2以上)
  minStart: 2

game:
  # 最終アイテム
  finalItem:
    totem: enable
  # 鬼のリスポーンまでの時間
  respawn: 5
  # イベントの周期
  event: 30
  # カウントダウン秒数
  countdown: 15
  # 残り何秒で発光を付与するか
  glow: 15
  # 時間(tick)
  day: 1000
  # バッテリー 特殊アイテムを使用できる回数
  maxBattery: 8
  # ゲーム開始時の位置
  startPos:
    x: 0
    y: 0
    z: 0
  # ロビーの位置
  lobbyPos:
    x: 0
    y: 0
    z: 0
  # 体力
  health:
    seeker: 40.0
    hider: 10.0

shop:
  # 各陣営の初期ポイント
  seekerDefault: 2
  hiderDefault: 1
  hiderGiveDelay: 60
  hidersAdd: 1
  seekersAdd: 1
  amount:
    # 各種特殊アイテムの価格
    flash: 1
    playersearcher: 1
    knockback_stick: 2
    battery_pack: 3

item:
  # アイテムの有効/無効化
  flash:
    state: disable
    duration: 10
  playersearcher:
    state: disable
    # Seeker Searcherが捜索する範囲の半径
    hiderSearches: 16
    seekerSearches: 16
  knockback_stick:
    state: disable
    level: 8
  battery_pack:
    state: disable

event:
  # イベントの有効/無効化
  GLOW_ALL:
    state: enable
    mode: hard,chaos
    duration: 10
  SPEEDUP:
    state: enable
    mode: normal,hard,chaos
    duration: 15
  JUMP_BOOST:
    state: enable
    mode: normal,hard,chaos
    duration: 15
  SHUFFLE:
    state: enable
    mode: hard,chaos
  BOOM:
    state: enable
    mode: chaos

message:
  item:
    playersearcher:
      seekerfound: "半径%sブロック以内に鬼がいます！"
      hiderFound: "半径%sブロック以内に逃げがいます！"
      notfound: "半径%sブロック以内にはいません。"
    noBattery: "バッテリー切れです！"
  shop:
    title: "ショップ"
    pointNotEnough: "ポイントが不足しています。"
    buy: "アイテム '%s' を購入しました！"
  command:
    fly:
      enable: "飛行を有効化しました。"
      disable: "飛行を無効化しました。"
    notfound: "コマンド %s の引数 %s は存在しません。"
    timer:
      help: "§l§aかくれんぼプラグイン - タイマーコマンド\n\n/timer start - タイマーをスタートします\n/timer stop - タイマーをストップします\n/timer pause - タイマーを一時停止します\n/timer set [整数] - タイマーの時間を設定します"
      alreadyStarted: "§l§cタイマーはすでにスタートしています。"
      start: "タイマーをスタートしました。"
      alreadyStopped: "§l§cタイマーはすでにストップしています。"
      stop: "タイマーがストップされました。"
      pause:
        1: "タイマーが一時停止されました。"
        2: "タイマーが再開されました。"
      setFailed: "§l§cタイマーの作動中は時間の変更はできません。"
      set: "タイマーの設定時間が%s秒に設定されました。"
      setDefault: "タイマーの設定時間がコンフィグのデフォルト(%s)に設定されました。"
      getCurrentSettings: "タイマーの設定時間は%s秒です。"
    hideandseek:
      help: "§l§aかくれんぼプラグイン - メインコマンド\n\n/hideandseek start [鬼の人数] - ゲームを開始します\n/hideandseek stop - ゲームを終了します\n/hideandseek setspawn [lobby|game] - 自分のいる位置にロビーまたはマップのスポーン位置を設定します\n/hideandseek settings - 現在の設定を表示します"
      alreadyStarted: "§l§cゲームはすでに開始しています。"
      alreadyStopped: "§l§cゲームはすでに終了しています。"
      overlimit: "鬼の数をプレイヤー数以上、または1以下にすることはできません。"
      setnumber: "値を指定してください。"
      setSpawn: "スポーン位置をX: %s, Y: %s, Z: %s に設定しました。"
      failedcustom: "HiderまたはSeekerはそれぞれ最低1人以上必要です。"
      modenotfound: "モード %s が見つかりません。モードは'normal' 'hard' 'chaos'のいずれかである必要があります。"
      settings:
        title: "- 現在の設定 -\n\n"
        players: "現在の人数: %s"
        hiders: "現在の設定済みの逃げの人数: %s"
        seekers: "現在の設定済みの鬼の人数: %s"
        spectates: "現在の設定済みの観戦者数: %s"
        items: "\n- 現在の特殊アイテムの状態 -\n\n"
        item:
          flash: "フラッシュ: %s"
        time: "\n- 時間設定 -"
        times:
          event: "現在のイベント周期: %s"
          countdown: "現在のカウントダウン秒数: %s"
      noargument: "引数が不足しています。"
    map:
      help: "§l§aかくれんぼプラグイン - Mapコマンド\n\n/map add [マップ名] [マップタイトル] [マップの時間] [マップのモード] - 現在の位置をスポーン地点とし、マップを追加します。"
    hider:
      help: "§l§aかくれんぼプラグイン - Hiderコマンド\n\n/hider add [プレイヤー] - プレイヤーをhiderに追加します\n/hider remove - プレイヤーをhiderから削除します"
      playernotfound: "プレイヤーが見つかりませんでした。"
    seeker:
      help: "§l§aかくれんぼプラグイン - Seekerコマンド\n\n/seeker add [プレイヤー] - プレイヤーをseekerに追加します\n/seeker remove - プレイヤーをseekerから削除します"
      playernotfound: "プレイヤーが見つかりませんでした。"
    spectate:
      help: "§l§aかくれんぼプラグイン - Spectateコマンド\n\n/spectate add [プレイヤー] - プレイヤーを観戦者に追加します\n/spectate remove - プレイヤーを観戦者から削除します"
      playernotfound: "プレイヤーが見つかりませんでした。"
    eventtester:
      help: "EventTester - For Debug"
    spectator:
      help: "§l§aかくれんぼプラグイン - Spectatorコマンド(Spectateとは別です)\n\n/spectator join - 観戦者になります\n/spectator leave - 観戦者から抜けます"
      changeFailed: "ゲーム中にチームを変更することはできません。"
      alreadyJoined: "すでに観戦者です。"
      alreadyLeaved: "観戦者ではありません。"
  mode:
    normal: "ノーマルモード。いつも通り。"
    hard: "ハードモード。鬼のアイテムが強化される。逃げには剣が配布される。"
    chaos: "カオスモード。全員が同じアイテムとエフェクトを付与される。鬼にやられる前に返り討ちにしよう。"
  game:
    getPoint: "%sポイントゲットしました！"
    useBattery: "バッテリーが全回復した！"
    timeup: "タイムアップ！！"
    title: "かくれんぼ"
    timer: "残り時間 : あと%s分%s秒"
    start: "ゲーム開始！鬼から隠れろ！"
    glow: "残り%s秒となったので、逃走者全員に発光が付与されます。"
    finalPlayer: "逃走者が残り一人となりました！最後の一人には、鬼と戦うためのアイテムが付与されます。(難易度によって配布されるアイテムは変わります。ピースフルモードでは特殊アイテムは配布されません。)"
    countdown: "開始まで残り%s秒"
    startCountdown: "ゲームを開始します..."
    hiderKilled: "%sは見つかってしまった！"
    seekerKilled: "鬼の%sは%sの逆襲にあった！"
    playerDeath: "%sは自殺した！"
    playerExplosion: "%sは爆発した！"
    forceEnd: "ゲームが管理者により強制終了されました。"
    hiderWin: "Hiders Win!"
    seekerWin: "Seekers Win!"
    gameEnd: "ゲーム終了！！"
    onepersonisenough: "の一人で十分だった。"
    survived: "生存者"
    survivedtimes: "は%s秒間鬼から隠れ続けた！"
    killedplayers: "は%s人を見つけた！"
    killedall: "は一人で全員を発見した。"
    selectedMap: "マップ: %s"
    selectedDifficulty: "モード: %s"
    selectedMapCredit: "クレジット: %s"
    respawnat: "あと%s秒でリスポーンします..."
  event:
    join: "§l§eかくれんぼへようこそ、%sさん！"
    leave: "§l§e%sさんが退出しました。"
  plugin:
    enable: "かくれんぼプラグインが有効化されました。"
    disable: "かくれんぼプラグインが無効化されました。"
    initialize: "Initializing Hide and Seek..."
  team:
    hiderPrefix: "逃げ"
    seekerPrefix: "鬼"
    visitorPrefix: "ロビー"
    deadPrefix: "死亡"
    specPrefix: "観戦者"
    waitingPrefix: "待機中"
  gameevent:
    speedup: "スピードアップ - 逃げの足が%s秒間早くなります。"
    jumpboost: "跳躍力 - 全員のジャンプ力が%s秒間上昇します。"
    glowall: "発光 - 全員が%s秒間発光します。"
    shuffle: "スワップ - 全員の位置がランダムに入れ替わります。"
    boom: "BOOM!!! - ランダムなプレイヤーが爆発します。"
  ui:
    settings:
      title: "ゲーム設定"
  lobby:
    playerNotEnough: "プレイヤーがあと%s人必要です..."
    countdown: "あと%s秒で開始します！"