name: Hide-and-Seek
version: '${project.version}'
main: io.github.akki.hideandseek.HideandSeek
api-version: '1.20'
load: STARTUP
authors: [akki697222]

commands:
  timer:
    description: Timer Command
    usage: /<command> [set|get|start|stop|pause] [time]
  hideandseek:
    description: Hide and Seek main Commands.
    usage: /<command> [start|end]
  seeker:
    description: Seeker
    usage: /<command> [add|remove]
  hider:
    description: Hider
    usage: /<command> [add|remove]
  spectate:
    description: Spectate
    usage: /<command> [add|remove]
  map:
    description: Map
    usage: /<command> [add] [name] [title]
  eventtester:
    description: For event testing
    usage: /<command> [eventName(Enum GameEvent.Events)]